### PR TITLE
Added support for Doctrine 2.6

### PR DESCRIPTION
**Pull request by NielsJanssen**
I've removed the max version to support newer versions of Doctrine. I've tested it and haven't encountered any issues.

### CODE REVIEW

**Comment by jvandesande** [comment]
I think it's better to limit the version to 2.* via `^2.3`, because `3.0` will probably introduce breaking changes.

**Comment by NielsJanssen** [comment]
@jvandesande You're right, I've added the constraint.

**Comment by jvandesande** [comment]
You should do the same for "doctrine/orm".

/cc @sandermarechal @rjbijl

**Comment by sandermarechal** [comment]
Fixed, thanks!

**Pull request closed without merging**
